<?php

namespace App\DataFixtures;

use App\DataFixtures\BrandFixtures;
use App\Entity\Model;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Faker\Factory;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class ModelFixtures extends Fixture implements DependentFixtureInterface
{
    public const MODELS = array(
        array(
            "nom" => "iPhone 12",
            "numero" => "12",
            "constructeur" => "Apple",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.1 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Noir",
            "camera_principale" => "12 MP",
            "camera_frontale" => "12 MP",
            "batterie" => "2815 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy S21",
            "numero" => "S21",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2021,
            "taille_ecran" => "6.2 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Gris",
            "camera_principale" => "64 MP",
            "camera_frontale" => "10 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "Google Pixel 5",
            "numero" => "5",
            "constructeur" => "Google",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Blanc",
            "camera_principale" => "12.2 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "4080 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy S20",
            "numero" => "S20",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.2 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "12 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "64 MP",
            "camera_frontale" => "10 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "iPhone 13 Pro",
            "numero" => "13 Pro",
            "constructeur" => "Apple",
            "annee_fabrication" => 2021,
            "taille_ecran" => "6.1 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "6 Go",
            "capacite_stockage" => "256 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Or",
            "camera_principale" => "12 MP",
            "camera_frontale" => "12 MP",
            "batterie" => "3095 mAh"
        ),
        array(
            "nom" => "OnePlus 9",
            "numero" => "9",
            "constructeur" => "OnePlus",
            "annee_fabrication" => 2021,
            "taille_ecran" => "6.55 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "48 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "4500 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy Note 20",
            "numero" => "Note 20",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.7 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "256 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Mystic Bronze",
            "camera_principale" => "64 MP",
            "camera_frontale" => "10 MP",
            "batterie" => "4300 mAh"
        ),
        array(
            "nom" => "iPhone SE",
            "numero" => "SE",
            "constructeur" => "Apple",
            "annee_fabrication" => 2020,
            "taille_ecran" => "4.7 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "3 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Rouge",
            "camera_principale" => "12 MP",
            "camera_frontale" => "7 MP",
            "batterie" => "1821 mAh"
        ),
        array(
            "nom" => "Google Pixel 6",
            "numero" => "6",
            "constructeur" => "Google",
            "annee_fabrication" => 2022,
            "taille_ecran" => "6.4 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Blanc",
            "camera_principale" => "50 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "4614 mAh"
        ),
        array(
            "nom" => "OnePlus 8 Pro",
            "numero" => "8 Pro 256 Go",
            "constructeur" => "OnePlus",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.78 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "12 Go",
            "capacite_stockage" => "256 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Vert",
            "camera_principale" => "48 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "4510 mAh"
        ),
        array(
            "nom" => "Xiaomi Mi 11",
            "numero" => "Mi 11",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.81 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "108 MP",
            "camera_frontale" => "20 MP",
            "batterie" => "4600 mAh"
        ),
        array(
            "nom" => "Sony Xperia 1 III",
            "numero" => "1 III",
            "constructeur" => "Sony",
            "annee_fabrication" => 2021,
            "taille_ecran" => "6.5 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "12 Go",
            "capacite_stockage" => "256 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "12 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "4500 mAh"
        ),
        array(
            "nom" => "LG Velvet",
            "numero" => "Velvet - Blanc",
            "constructeur" => "LG",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.8 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Blanc",
            "camera_principale" => "48 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "4300 mAh"
        ),
        array(
            "nom" => "Nokia 8.3 5G",
            "numero" => "8.3 5G",
            "constructeur" => "Nokia",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.81 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "64 MP",
            "camera_frontale" => "24 MP",
            "batterie" => "4500 mAh"
        ),
        array(
            "nom" => "Oppo Find X3 Pro",
            "numero" => "Find X3 Pro",
            "constructeur" => "Oppo",
            "annee_fabrication" => 2021,
            "taille_ecran" => "6.7 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "12 Go",
            "capacite_stockage" => "256 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "50 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "4500 mAh"
        ),
        array(
            "nom" => "Xiaomi Redmi Note 10",
            "numero" => "Redmi Note 10",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2021,
            "taille_ecran" => "6.43 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "48 MP",
            "camera_frontale" => "13 MP",
            "batterie" => "5000 mAh"
        ),
        array(
            "nom" => "Motorola Edge",
            "numero" => "Edge",
            "constructeur" => "Motorola",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.7 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "64 MP",
            "camera_frontale" => "25 MP",
            "batterie" => "4500 mAh"
        ),
        array(
            "nom" => "Huawei Mate 40 Pro",
            "numero" => "Mate 40 Pro",
            "constructeur" => "Huawei",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.76 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "256 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "50 MP",
            "camera_frontale" => "13 MP",
            "batterie" => "4400 mAh"
        ),
        array(
            "nom" => "Xiaomi Mi 10T Pro",
            "numero" => "Mi 10T Pro",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.67 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "108 MP",
            "camera_frontale" => "20 MP",
            "batterie" => "5000 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy A71",
            "numero" => "A71 - 2020",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.7 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "64 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "4500 mAh"
        ),
        array(
            "nom" => "iPhone 12 Mini",
            "numero" => "12 Mini",
            "constructeur" => "Apple",
            "annee_fabrication" => 2020,
            "taille_ecran" => "5.4 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Bleu",
            "camera_principale" => "12 MP",
            "camera_frontale" => "12 MP",
            "batterie" => "2227 mAh"
        ),
        array(
            "nom" => "LG Wing",
            "numero" => "Wing",
            "constructeur" => "LG",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.8 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "64 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "Motorola Razr",
            "numero" => "Razr",
            "constructeur" => "Motorola",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.2 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "48 MP",
            "camera_frontale" => "20 MP",
            "batterie" => "2800 mAh"
        ),
        array(
            "nom" => "Nokia 5.4",
            "numero" => "5.4",
            "constructeur" => "Nokia",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.39 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "48 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "Huawei Nova 7",
            "numero" => "Nova 7",
            "constructeur" => "Huawei",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.53 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "64 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "Oppo Reno5",
            "numero" => "Reno5",
            "constructeur" => "Oppo",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.43 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "64 MP",
            "camera_frontale" => "44 MP",
            "batterie" => "4300 mAh"
        ),
        array(
            "nom" => "Xiaomi Mi Note 10",
            "numero" => "Mi Note 10",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.47 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "108 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "5260 mAh"
        ),
        array(
            "nom" => "Sony Xperia 10 II",
            "numero" => "10 II",
            "constructeur" => "Sony",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.0 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "12 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "3600 mAh"
        ),
        array(
            "nom" => "LG K61",
            "numero" => "K61",
            "constructeur" => "LG",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.53 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Blanc",
            "camera_principale" => "48 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "Motorola Moto G Stylus",
            "numero" => "G Stylus",
            "constructeur" => "Motorola",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.4 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "48 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "Nokia 7.2",
            "numero" => "7.2 - Noir",
            "constructeur" => "Nokia",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.3 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "48 MP",
            "camera_frontale" => "20 MP",
            "batterie" => "3500 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy M31",
            "numero" => "M31",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.4 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "64 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "6000 mAh"
        ),
        array(
            "nom" => "iPhone SE (2020)",
            "numero" => "SE (2020) - Noir",
            "constructeur" => "Apple",
            "annee_fabrication" => 2020,
            "taille_ecran" => "4.7 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "3 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Noir",
            "camera_principale" => "12 MP",
            "camera_frontale" => "7 MP",
            "batterie" => "1821 mAh"
        ),
        array(
            "nom" => "Xiaomi Redmi Note 9 Pro",
            "numero" => "Redmi Note 9 Pro",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.67 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Gris",
            "camera_principale" => "64 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "5020 mAh"
        ),
        array(
            "nom" => "OnePlus 8 Pro",
            "numero" => "8 Pro 128 Go",
            "constructeur" => "OnePlus",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.78 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Vert",
            "camera_principale" => "48 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "4510 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy A51",
            "numero" => "A51 - Blanc",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.5 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Blanc",
            "camera_principale" => "48 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "iPhone 11 Pro",
            "numero" => "11 Pro",
            "constructeur" => "Apple",
            "annee_fabrication" => 2019,
            "taille_ecran" => "5.8 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "256 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Gris",
            "camera_principale" => "12 MP",
            "camera_frontale" => "12 MP",
            "batterie" => "3046 mAh"
        ),
        array(
            "nom" => "Google Pixel 4a",
            "numero" => "Pixel 4a",
            "constructeur" => "Google",
            "annee_fabrication" => 2020,
            "taille_ecran" => "5.81 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "12.2 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "3140 mAh"
        ),
        array(
            "nom" => "Xiaomi Redmi 9",
            "numero" => "Redmi 9",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.53 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "13 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "5020 mAh"
        ),
        array(
            "nom" => "Sony Xperia 5 II",
            "numero" => "5 II",
            "constructeur" => "Sony",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.1 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "12 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "LG V60 ThinQ",
            "numero" => "V60 ThinQ",
            "constructeur" => "LG",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.8 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "64 MP",
            "camera_frontale" => "10 MP",
            "batterie" => "5000 mAh"
        ),
        array(
            "nom" => "Motorola Moto G Power",
            "numero" => "G Power",
            "constructeur" => "Motorola",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.4 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "16 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "5000 mAh"
        ),
        array(
            "nom" => "Nokia 6.2",
            "numero" => "6.2",
            "constructeur" => "Nokia",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.3 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Gris",
            "camera_principale" => "16 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "3500 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy A71",
            "numero" => "A71 - 2019",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.7 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "64 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "4500 mAh"
        ),
        array(
            "nom" => "iPhone XR",
            "numero" => "XR - Blanc",
            "constructeur" => "Apple",
            "annee_fabrication" => 2018,
            "taille_ecran" => "6.1 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "3 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Blanc",
            "camera_principale" => "12 MP",
            "camera_frontale" => "7 MP",
            "batterie" => "2942 mAh"
        ),
        array(
            "nom" => "Google Pixel 5",
            "numero" => "Pixel 5",
            "constructeur" => "Google",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.0 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "12.2 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "4080 mAh"
        ),
        array(
            "nom" => "Xiaomi Redmi Note 8 Pro",
            "numero" => "Redmi Note 8 Pro",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.53 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Vert",
            "camera_principale" => "64 MP",
            "camera_frontale" => "20 MP",
            "batterie" => "4500 mAh"
        ),
        array(
            "nom" => "OnePlus 7T",
            "numero" => "7T",
            "constructeur" => "OnePlus",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.55 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Gris",
            "camera_principale" => "48 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "3800 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy S20 FE",
            "numero" => "S20 FE",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.5 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "12 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "4500 mAh"
        ),
        array(
            "nom" => "iPhone 11",
            "numero" => "11",
            "constructeur" => "Apple",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.1 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Noir",
            "camera_principale" => "12 MP",
            "camera_frontale" => "12 MP",
            "batterie" => "3110 mAh"
        ),
        array(
            "nom" => "Google Pixel 3a",
            "numero" => "Pixel 3a",
            "constructeur" => "Google",
            "annee_fabrication" => 2019,
            "taille_ecran" => "5.6 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "12.2 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "3000 mAh"
        ),
        array(
            "nom" => "Xiaomi Redmi Note 7",
            "numero" => "Redmi Note 7",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.3 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "48 MP",
            "camera_frontale" => "13 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "OnePlus Nord",
            "numero" => "Nord",
            "constructeur" => "OnePlus",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.44 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "48 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "4115 mAh"
        ),
        array(
            "nom" => "Sony Xperia 1 II",
            "numero" => "1 II",
            "constructeur" => "Sony",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.5 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "256 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "12 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "LG Velvet",
            "numero" => "Velvet - Gris",
            "constructeur" => "LG",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.8 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Gris",
            "camera_principale" => "48 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "4300 mAh"
        ),
        array(
            "nom" => "Motorola Moto G7 Power",
            "numero" => "G7 Power",
            "constructeur" => "Motorola",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.2 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "3 Go",
            "capacite_stockage" => "32 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "12 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "5000 mAh"
        ),
        array(
            "nom" => "Nokia 7.2",
            "numero" => "7.2 - Gris",
            "constructeur" => "Nokia",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.3 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Gris",
            "camera_principale" => "48 MP",
            "camera_frontale" => "20 MP",
            "batterie" => "3500 mAh"
        ),
        array(
            "nom" => "Huawei P40 Pro",
            "numero" => "P40 Pro",
            "constructeur" => "Huawei",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.58 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "256 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "50 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "4200 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy A51",
            "numero" => "A51 - Noir",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.5 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "48 MP",
            "camera_frontale" => "32 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "iPhone SE (2020)",
            "numero" => "SE (2020) - Rouge",
            "constructeur" => "Apple",
            "annee_fabrication" => 2020,
            "taille_ecran" => "4.7 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "3 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Rouge",
            "camera_principale" => "12 MP",
            "camera_frontale" => "7 MP",
            "batterie" => "1821 mAh"
        ),
        array(
            "nom" => "Xiaomi Mi 10",
            "numero" => "Mi 10",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2020,
            "taille_ecran" => "6.67 pouces",
            "reseau_cellulaire" => "5G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "108 MP",
            "camera_frontale" => "20 MP",
            "batterie" => "4780 mAh"
        ),
        array(
            "nom" => "OnePlus 6T",
            "numero" => "6T",
            "constructeur" => "OnePlus",
            "annee_fabrication" => 2018,
            "taille_ecran" => "6.41 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "16 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "3700 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy S10",
            "numero" => "S10",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.1 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "8 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Blanc",
            "camera_principale" => "12 MP",
            "camera_frontale" => "10 MP",
            "batterie" => "3400 mAh"
        ),
        array(
            "nom" => "iPhone XS",
            "numero" => "XS",
            "constructeur" => "Apple",
            "annee_fabrication" => 2018,
            "taille_ecran" => "5.8 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Gris",
            "camera_principale" => "12 MP",
            "camera_frontale" => "7 MP",
            "batterie" => "2658 mAh"
        ),
        array(
            "nom" => "Google Pixel 3 XL",
            "numero" => "Pixel 3 XL",
            "constructeur" => "Google",
            "annee_fabrication" => 2018,
            "taille_ecran" => "6.3 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Blanc",
            "camera_principale" => "12.2 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "3430 mAh"
        ),
        array(
            "nom" => "Xiaomi Redmi Note 5",
            "numero" => "Redmi Note 5",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2018,
            "taille_ecran" => "5.99 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "12 MP",
            "camera_frontale" => "5 MP",
            "batterie" => "4000 mAh"
        ),
        array(
            "nom" => "OnePlus 5T",
            "numero" => "5T",
            "constructeur" => "OnePlus",
            "annee_fabrication" => 2017,
            "taille_ecran" => "6.01 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "16 MP",
            "camera_frontale" => "16 MP",
            "batterie" => "3300 mAh"
        ),
        array(
            "nom" => "Samsung Galaxy S9",
            "numero" => "S9",
            "constructeur" => "Samsung",
            "annee_fabrication" => 2018,
            "taille_ecran" => "5.8 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "12 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "3000 mAh"
        ),
        array(
            "nom" => "iPhone XR",
            "numero" => "XR - Bleu",
            "constructeur" => "Apple",
            "annee_fabrication" => 2018,
            "taille_ecran" => "6.1 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "3 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "iOS",
            "couleur" => "Bleu",
            "camera_principale" => "12 MP",
            "camera_frontale" => "7 MP",
            "batterie" => "2942 mAh"
        ),
        array(
            "nom" => "Google Pixel 2 XL",
            "numero" => "Pixel 2 XL",
            "constructeur" => "Google",
            "annee_fabrication" => 2017,
            "taille_ecran" => "6 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "4 Go",
            "capacite_stockage" => "64 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Noir",
            "camera_principale" => "12.2 MP",
            "camera_frontale" => "8 MP",
            "batterie" => "3520 mAh"
        ),
        array(
            "nom" => "Xiaomi Mi 9",
            "numero" => "Mi 9",
            "constructeur" => "Xiaomi",
            "annee_fabrication" => 2019,
            "taille_ecran" => "6.39 pouces",
            "reseau_cellulaire" => "4G",
            "ram" => "6 Go",
            "capacite_stockage" => "128 Go",
            "systeme_exploitation" => "Android",
            "couleur" => "Bleu",
            "camera_principale" => "48 MP",
            "camera_frontale" => "20 MP",
            "batterie" => "3300 mAh"
        )
    );
    public function load(ObjectManager $manager): void
    {
        $faker = Factory::create('fr_FR');
        foreach (self::MODELS as $key => $itemModel) {
            $model = new Model();
            $model->setName($itemModel['nom']);
            $model->setCodeNumber($itemModel['numero']);
            $model->setBasePrice($faker->numberBetween(1, 80));
            $model->setBrand($this->getReference('Brand_' . strtoupper($itemModel['constructeur'])));
            $manager->persist($model);
            $this->addReference('Model_' . trim($itemModel['numero']), $model);
        }

        $manager->flush();
    }

    public function getDependencies()
    {
        return [
            BrandFixtures::class,
        ];
    }
}
